server:
  port: 8999
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:postgres://ec2-54-243-211-197.compute-1.amazonaws.com:5432/deutdjeanuuo2f
    username: ingbyrijfusitb
    password: 18cffd48c1cb179ac9a7111279c6f31ed17af43beb25c0756fbbbae899e6267c
    driver-class-name: org.postgresql.Driver
    
eureka:
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    service-url:
      defaultZone: https://eureka-unialfa.herokuapp.com/eureka/
    healthcheck: true