server:
  port: 8999
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://localhost:3306/pos_database_usuario?createDatabaseIfNotExist=true
    username: pos
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck: true