zuul:
  routes:
    usuarios:
      path: /usuarios/**
      serviceId: usuarios
    tarefas:
      path: /tarefas/**
      serviceId: tarefas
eureka:
  client:
    service-url:
      defaultZone: https://eureka-unialfa.herokuapp.com:8761/eureka/
    healthcheck: true