zuul:
  routes:
    usuarios:
      path: /usuarios/**
      serviceId: usuarios
    tarefas:
      path: /tarefas/**
      serviceId: tarefas
eureka:
  instance:
    securePortEnabled: true
  client:
    service-url:
      defaultZone: https://eureka-unialfa.herokuapp.com/eureka/
    healthcheck: true
ribbon:
  IsSecure: true
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000