zuul:
  routes:
    usuarios:
      path: /usuarios/**
      serviceId: usuarios
    tarefas:
      path: /tarefas/**
      serviceId: tarefas
eureka:
  instance:
    hostname: zuul-unialfa.herokuapp.com
    secure-port-enabled: true
    non-secure-port-enabled: false
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    service-url:
      defaultZone: https://eureka-unialfa.herokuapp.com/eureka/
    healthcheck: true

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000