server:
  port: 9001 
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource: 
    url: jdbc:mysql://localhost:3306/pos_db_distribuido_spa?createDatabaseIfNotExist=true
    username: pos
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
service:
  uri: http://localhost:9000/ws/service