server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 1000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck: true
logging:
  level:
    com:
      netflix:
        eureka: false
        discovery: false