server:
  port: 9000
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:postgres://ec2-54-243-211-197.compute-1.amazonaws.com:5432/d36f7dc63oe6hr
    username: vylqimmbpazgwq
    password: 21557cda0285f96343e3d1efbd77bb6384473a6bc842fc4776b9465091ea58f4
    driver-class-name: org.postgresql.Driver
    
eureka:
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    service-url:
      defaultZone: https://eureka-unialfa.herokuapp.com/eureka/
    healthcheck: true